#!/usr/bin/env python3
"""
Daily briefings generator for Cole.ai dashboard.

Usage:
  python briefings_update.py

Requires:
  pip install anthropic
  ANTHROPIC_API_KEY environment variable set

Run this each morning. It writes daily_briefings.js into the dashboard folder,
which the app loads automatically on next page open/refresh.
"""

import anthropic
import json
import os
import re
import sys
from datetime import date

TODAY = date.today().isoformat()
DASHBOARD_DIR = os.path.dirname(os.path.abspath(__file__))
OUTPUT_PATH = os.path.join(DASHBOARD_DIR, "daily_briefings.js")

PROMPT = f"""Today is {TODAY}. Generate a daily news briefing for Cole, a Chemical Engineering junior at Notre Dame interested in industry careers, energy, biotech, and global markets.

Search for 6 real news articles published within the past 24 hours (today or yesterday only — no older). Find one article per category:

1. Politics — major US or global political development
2. Tech — AI, semiconductors, software, or tech industry news
3. Chemical Engineering — process engineering, chemicals, materials, energy tech, or relevant manufacturing
4. Markets — stock market, economy, commodities, or macro finance
5. Science — biology, physics, chemistry, climate, or significant research findings
6. World — significant international news outside the US

For each article, return a JSON object with exactly these fields:
  category    — one of the 6 categories above (exact spelling)
  headline    — the actual article headline, verbatim
  source      — publication name (e.g. Reuters, WSJ, Nature, Chemical Engineering)
  link        — full URL to the article
  whyItMatters — 1-2 sentences on why this matters to a ChemE student

Return ONLY a valid JSON array of exactly 6 objects. No markdown, no explanation, just the array."""


def generate_briefings():
    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if not api_key:
        sys.exit("Error: ANTHROPIC_API_KEY environment variable not set.\n"
                 "Set it with: set ANTHROPIC_API_KEY=sk-ant-...")

    client = anthropic.Anthropic(api_key=api_key)

    print(f"Searching for today's articles ({TODAY})...")
    response = client.messages.create(
        model="claude-opus-4-7",
        max_tokens=4096,
        tools=[{"type": "web_search_20250305", "name": "web_search"}],
        messages=[{"role": "user", "content": PROMPT}],
    )

    # Pull text from the final assistant turn
    text = ""
    for block in response.content:
        if hasattr(block, "text"):
            text += block.text

    # Extract the JSON array
    match = re.search(r"\[.*\]", text, re.DOTALL)
    if not match:
        sys.exit(f"Error: Could not find JSON array in response.\nResponse was:\n{text}")

    try:
        briefings = json.loads(match.group())
    except json.JSONDecodeError as e:
        sys.exit(f"Error: Could not parse JSON: {e}\nRaw text:\n{text}")

    return briefings


def write_js(briefings):
    entries = []
    for i, b in enumerate(briefings):
        entries.append({
            "id": f"auto-{TODAY}-{i + 1}",
            "date": TODAY,
            "category": b.get("category", "World"),
            "headline": b.get("headline", ""),
            "source": b.get("source", ""),
            "link": b.get("link", ""),
            "whyItMatters": b.get("whyItMatters", ""),
        })

    js_entries = json.dumps(entries, indent=2, ensure_ascii=False)

    js = f"""// Auto-generated by briefings_update.py — {TODAY}
// Do not edit manually.
(function () {{
  var todayBriefings = {js_entries};

  document.addEventListener('DOMContentLoaded', function () {{
    var raw = localStorage.getItem('briefings');
    var existing = raw ? JSON.parse(raw) : [];
    var existingIds = new Set(existing.map(function (b) {{ return b.id; }}));
    var toAdd = todayBriefings.filter(function (b) {{ return !existingIds.has(b.id); }});
    if (toAdd.length > 0) {{
      localStorage.setItem('briefings', JSON.stringify(existing.concat(toAdd)));
      if (typeof App !== 'undefined') {{
        App.renderBriefings();
        App.renderToday();
      }}
    }}
  }});
}})();
"""

    with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
        f.write(js)

    print(f"\n✓ Wrote {len(entries)} briefings to daily_briefings.js\n")
    for b in entries:
        print(f"  [{b['category']:22s}] {b['headline'][:65]}")
    print("\nRefresh Cole.ai in your browser to see today's briefings.")


if __name__ == "__main__":
    briefings = generate_briefings()
    write_js(briefings)
