// Auto-generated by briefings_update.py — 2026-09-29
// Do not edit manually.
(function () {
  var todayBriefings = [
  {
    "id": "auto-2026-09-29-1",
    "date": "2026-09-29",
    "category": "Politics",
    "headline": "Embarrassing Breach at F.B.I. Fuels Fears of Harm to Its Employees",
    "source": "GoLocalProv",
    "link": "https://www.google.com/search?q=Embarrassing+Breach+at+F.B.I.+Fuels+Fears+of+Harm+to+Its+Employees+GoLocalProv",
    "whyItMatters": "This highlights the critical importance of cybersecurity in government and industry, a field where chemical engineers might contribute to securing industrial control systems or sensitive research data, especially in critical infrastructure sectors."
  },
  {
    "id": "auto-2026-09-29-2",
    "date": "2026-09-29",
    "category": "Chemical Engineering",
    "headline": "3D-printed, solid-state bioreactor converts methane waste to useful chemicals",
    "source": "Lawrence Livermore National Laboratory",
    "link": "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQFyqyOic_M250XEggabrRZBetMHpa3JVhML1eArnS6DSK3IFPShSKXqCzVVxKPquppM8AbQuaX9NcOFNT5gun6UdXPt3gP_0cOHrG0RejdtV_I00NG9KGT9lNYS8uf541fcuuCQkfT1jh0=",
    "whyItMatters": "This development showcases innovative approaches to sustainable chemical processes and waste valorization, utilizing advanced manufacturing techniques like 3D printing, which are increasingly relevant for chemical engineers in industry and energy sectors."
  },
  {
    "id": "auto-2026-09-29-3",
    "date": "2026-09-29",
    "category": "Tech",
    "headline": "AI coding agents are raising the stakes for SAST",
    "source": "Developer",
    "link": "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQHfPWxw90BBlZ9ZFyO8j83f-GLPgwOVVKqrllt8jLPLb4MfZ95R8Bnd__5yjOBAVuueWgOEQPhRPRhYEAXuWqke2BI3UFP9A0_nMkGaK3XR60QMiy3z5FGRLA==",
    "whyItMatters": "As AI becomes more integrated into software development, chemical engineers working in process control, simulation, or data analysis will need to understand how AI-generated code impacts security and how to ensure the reliability and safety of these systems."
  }
];
  try {
    var raw = localStorage.getItem('briefings');
    var existing = raw ? JSON.parse(raw) : [];
    var filtered = existing.filter(function (b) { return b.date !== '2026-09-29'; });
    localStorage.setItem('briefings', JSON.stringify(filtered.concat(todayBriefings)));
    if (typeof Sync !== 'undefined' && Sync.schedulePush) Sync.schedulePush();
    if (typeof App !== 'undefined' && App.renderBriefings) {
      App.renderBriefings();
      App.renderToday();
    }
  } catch(e) {}
})();
