// Auto-generated by briefings_update.py — 2026-06-21
// Do not edit manually.
(function () {
  var todayBriefings = [
  {
    "id": "auto-2026-06-21-1",
    "date": "2026-06-21",
    "category": "Politics",
    "headline": "US-Iran talks in Switzerland: Is Lebanon top of agenda; who is attending?",
    "source": "Al Jazeera",
    "link": "https://www.aljazeera.com/news/2026/6/21/us-iran-talks-in-switzerland-is-lebanon-top-of-agenda-who-is-attending",
    "whyItMatters": "This article details the ongoing high-level technical talks between the US and Iran in Switzerland, focusing on the implementation of a recent memorandum of understanding and the critical issue of a ceasefire in Lebanon. For a Chemical Engineering student, understanding geopolitical stability, especially concerning major oil-producing regions like the Middle East and strategic waterways like the Strait of Hormuz, is crucial for comprehending global energy markets and supply chain risks in the chemical industry."
  },
  {
    "id": "auto-2026-06-21-2",
    "date": "2026-06-21",
    "category": "Chemical Engineering",
    "headline": "New heat-regulating fabric feels fluffy like cotton — but doesn't get wet",
    "source": "ScienceDaily",
    "link": "https://www.sciencedaily.com/releases/2026/06/260617112345.htm",
    "whyItMatters": "This breakthrough in materials science describes a novel synthetic fiber that mimics cotton's feel while repelling water and regulating heat more effectively. This is highly relevant to chemical engineers as it involves the design and synthesis of new polymers and phase-change materials for advanced textile applications, impacting industries from apparel to protective gear and potentially energy efficiency."
  },
  {
    "id": "auto-2026-06-21-3",
    "date": "2026-06-21",
    "category": "Tech",
    "headline": "Applied Materials Unveils Deposition and Selective Etch Systems to Advance 3D Chip Scaling",
    "source": "Barchart.com",
    "link": "https://www.barchart.com/story/news/22055106/applied-materials-unveils-deposition-and-selective-etch-systems-to-advance-3d-chip-scaling",
    "whyItMatters": "This article highlights advancements in semiconductor manufacturing, specifically new deposition and etch systems for creating complex 3D chip structures. For a Chemical Engineering student, this is vital as it showcases the critical role of materials engineering and process control in developing next-generation AI chips, offering insights into high-tech manufacturing careers and the intersection of chemistry with advanced computing hardware."
  }
];
  try {
    var raw = localStorage.getItem('briefings');
    var existing = raw ? JSON.parse(raw) : [];
    var filtered = existing.filter(function (b) { return b.date !== '2026-06-21'; });
    localStorage.setItem('briefings', JSON.stringify(filtered.concat(todayBriefings)));
    if (typeof Sync !== 'undefined' && Sync.schedulePush) Sync.schedulePush();
    if (typeof App !== 'undefined' && App.renderBriefings) {
      App.renderBriefings();
      App.renderToday();
    }
  } catch(e) {}
})();
